# frontend/app.py
import streamlit as st
import requests

# Configure page parameters
st.set_page_config(page_title="AI Support Copilot Workspace", layout="wide")

BACKEND_URL = "http://127.0.0.1:8000/api/tickets/process"

st.title("🤖 Customer Support AI Copilot Dashboard")
st.caption("Empowering support teams with automated context collection, RAG, and memory retention.")
st.markdown("---")

# 1. Create Mock Queued Tickets for testing inside the UI
mock_tickets = [
    {
        "id": "TICKET-01",
        "customer_id": "CUST_101",
        "title": "Delayed Shipment Inquiry",
        "text": "Hey, my order ORD_1042 hasn't arrived yet and I'm super stressed. Can you please check where it is? Also, remember to notify me via email only!"
    },
    {
        "id": "TICKET-02",
        "customer_id": "CUST_102",
        "title": "Return Policy & General Greeting",
        "text": "Hello, I just received my office chair (ORD_1043) but it doesn't match my desk height. Am I allowed to return it for a refund? What is the window?"
    }
]

# Layout split: Left Side for Ticket List, Right Side for Copilot Analysis
col_left, col_right = st.columns([1, 2])

with col_left:
    st.subheader("📥 Active Ticket Queue")
    
    # Loop through and create a clickable card for each ticket
    for ticket in mock_tickets:
        with st.container(border=True):
            st.write(f"**{ticket['id']}**: {ticket['title']}")
            st.caption(f"Customer ID: {ticket['customer_id']}")
            
            # Button to load this specific ticket into the workspace core
            if st.button(f"Analyze Workspace", key=ticket['id']):
                st.session_state["active_ticket"] = ticket
                # Clear past runs
                if "agent_response" in st.session_state:
                    del st.session_state["agent_response"]

# 2. Right Side Panel: Processing Workspace Core
with col_right:
    st.subheader("🛠️ Copilot Live Analysis Workspace")
    
    if "active_ticket" in st.session_state:
        current = st.session_state["active_ticket"]
        
        # Display the text of the raw incoming ticket
        st.info(f"**Processing Ticket Text:**\n\n\"{current['text']}\"")
        
        # Button to trigger our FastAPI agent backend route
        if st.button("🚀 Generate AI Insights & Response Draft", type="primary"):
            with st.spinner("Agentic pipeline collecting database contexts, memory, and RAG matrices..."):
                try:
                    payload = {
                        "customer_id": current["customer_id"],
                        "ticket_text": current["text"]
                    }
                    response = requests.post(BACKEND_URL, json=payload)
                    
                    if response.status_code == 200:
                        st.session_state["agent_response"] = response.json()
                        st.success("Analysis complete!")
                    else:
                        st.error(f"Backend Server returned an error code: {response.status_code}")
                except Exception as e:
                    st.error(f"Failed to connect to the FastAPI agent node: {e}")
        
        # 3. Render the full data response matrices returned by the FastAPI engine
        if "agent_response" in st.session_state:
            data = st.session_state["agent_response"]
            
            st.markdown("### 📊 Collected System Context Metrics")
            metric_col1, metric_col2, metric_col3 = st.columns(3)
            
            with metric_col1:
                st.warning("**CRM Profile Details:**")
                st.write(data.get("profile", "No metrics found."))
            
            with metric_col2:
                st.info("**Fulfillment Tracking:**")
                st.write(data.get("live_metrics", "No metrics found."))
                
            with metric_col3:
                st.success("**Recovered History (Memory):**")
                st.write(data.get("remembered_history", "No context found."))
            
            st.markdown("---")
            st.markdown("### 📝 AI Agent Summary & Proposed Resolution")
            
            # The final output generated by the LLM
            st.text_area(
                label="Ready to review output (Internal Summary & Draft Email Response):",
                value=data.get("summary_and_draft", ""),
                height=400
            )
            
            if st.button("📬 Click to Send Reply (Simulated)"):
                st.balloons()
                st.success("Draft processed and response updated successfully!")
                
    else:
        st.write("← Select an active incoming ticket from the left-side queue to begin the workflow process.")